#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=5

banner "Attach meme.sein.moe to Strapi Admin"

say "Target: https://meme.sein.moe → Vercel Admin; https://cms.sein.moe stays the API."
say "This retires the dead Payload reverse proxy (1Panel → 127.0.0.1:13000)."
warn "Do not point meme.sein.moe back at louis. Do not change the cms.sein.moe site."

# ── Stage 1 ───────────────────────────────────────────────────────────────
stage "Vercel — add meme.sein.moe"
say "Add the custom domain on the cms Admin project (the one serving cms-sepia-beta.vercel.app)."
open_url "https://vercel.com/dashboard"
step "Open the cms project (Git repo K4F7/cms / domain cms-sepia-beta.vercel.app)."
step "Settings → Domains → Add → meme.sein.moe."
step "Copy the CNAME target Vercel shows. It is usually cname.vercel-dns.com."
ask VERCEL_CNAME_TARGET "Paste the CNAME target (Enter if it is cname.vercel-dns.com):"
if [[ -z "$VERCEL_CNAME_TARGET" ]]; then
  VERCEL_CNAME_TARGET="cname.vercel-dns.com"
fi
note "Will use CNAME target: $VERCEL_CNAME_TARGET"
pause "Press Enter after Vercel lists meme.sein.moe (Invalid until DNS is next)."

# ── Stage 2 ───────────────────────────────────────────────────────────────
stage "Cloudflare — point meme at Vercel"
say "Replace the old Payload origin with a grey-cloud CNAME to Vercel."
open_url "https://dash.cloudflare.com"
step "Open zone sein.moe → DNS → Records."
step "Find the meme record (A/AAAA/CNAME). Do not edit cms."
step "Change it to: Type CNAME, Name meme, Target $VERCEL_CNAME_TARGET."
step "Set Proxy status to DNS only (grey cloud) so Vercel can issue the certificate."
step "Delete extra A/AAAA rows for the same name if they remain."
pause "Press Enter after the meme record is a grey-cloud CNAME."

# ── Stage 3 ───────────────────────────────────────────────────────────────
stage "1Panel — stop the Payload website"
say "meme.sein.moe used to reverse-proxy Payload on louis: 127.0.0.1:13000."
say "1Panel listens on the VPS loopback (GitHub var ONEPANEL_BASE_URL=http://127.0.0.1:52100)."
step "SSH to louis."
step "1Panel → Website → find meme.sein.moe → Stop or Delete."
step "Do not stop or edit the cms.sein.moe OpenResty site."
step "Containers: stop anything still published on :13000 or named payload / archive-payload."
if confirm "Type y after the Payload website/container is stopped"; then
  note "Payload ingress retired."
else
  warn "Leave this until the old :13000 site is gone, or Vercel and 1Panel will fight over the name if DNS is still orange-clouded to louis."
fi

# ── Stage 4 ───────────────────────────────────────────────────────────────
stage "louis — ADMIN_ORIGIN and recreate API"
say "CORS allowlist lives in /opt/cms/deploy/.env on louis, not in git."
say "GitHub Environment production already has ADMIN_ORIGIN=https://meme.sein.moe."
step "On louis, set the env and recreate the API container:"
note "sudo sed -i 's|^ADMIN_ORIGIN=.*|ADMIN_ORIGIN=https://meme.sein.moe|' /opt/cms/deploy/.env"
note "grep '^ADMIN_ORIGIN=' /opt/cms/deploy/.env"
note "cd /opt/cms/deploy && sudo docker compose -f compose.yml up -d --no-build --force-recreate api"
note "curl -sS http://127.0.0.1:1337/health"
pause "Press Enter after health returns status ok."

# ── Stage 5 ───────────────────────────────────────────────────────────────
stage "Verify Admin origin"
say "Check certificate, CORS, then log in from a real browser."
open_url "https://meme.sein.moe"
step "Confirm the Strapi Admin login page loads over HTTPS (not Cloudflare 525)."
step "From this machine you can also run:"
note "curl -sSI https://meme.sein.moe"
note "curl -sS -D - -o NUL -H \"Origin: https://meme.sein.moe\" https://cms.sein.moe/admin/init"
step "The API response must include Access-Control-Allow-Origin: https://meme.sein.moe and Allow-Credentials: true."
step "Log in as Archive Administrator, then reload the page and confirm the session stays."
pause "Press Enter after login + reload works."

finish
note "Next: on a trusted cert, CMS_REQUIRE_BROWSER_SESSION=1 npm test against cms.sein.moe / meme.sein.moe."
note "Issue: https://github.com/K4F7/cms/issues/31"
